# Generated by Django 3.2.13 on 2024-03-02 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('weather_description', models.CharField(max_length=255)),
                ('wind_speed', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('weather_icon', models.CharField(max_length=20)),
                ('api_response_id', models.IntegerField()),
                ('timezone', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
            ],
        ),
    ]
