# Generated by Django 3.2.13 on 2024-06-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainProperty',
            fields=[
                ('domain_property_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('postcost', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=255)),
                ('bathroom', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_id', models.CharField(max_length=255)),
                ('listing_url', models.URLField()),
                ('first_listed_date', models.DateTimeField()),
                ('floorplan_url', models.URLField(blank=True, null=True)),
                ('price_guide_url', models.URLField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('unit', 'Unit'), ('townhouse', 'Townhouse'), ('apartment', 'Apartment'), ('duplex', 'Duplex')], default='house', max_length=50)),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('domain_property_id', 'listing_id')},
            },
        ),
    ]
