# Generated by Django 3.2.13 on 2024-06-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainproperty',
            options={'ordering': ['create_ts']},
        ),
    ]
