# Generated by Django 3.2.13 on 2024-06-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_domainproperty_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domainproperty',
            table='domain_property',
        ),
    ]
